# Generated by Django 4.1.5 on 2023-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course_name',
            field=models.CharField(default='Nursing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='current_occupation_or_industry',
            field=models.CharField(default='Student', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='desired_occupation_or_industry',
            field=models.CharField(default='Nurse', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='educational_institution',
            field=models.CharField(default='Curtin University', max_length=100),
            preserve_default=False,
        ),
    ]
