# Generated by Django 4.1.5 on 2023-03-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_campaign_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
