# Generated by Django 4.1.5 on 2023-03-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_campaign_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='pledge_amount',
            new_name='amount',
        ),
    ]
